services:
  acudirtservice:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Issuer=Acudir.Test.Dev
      - Jwt__Audience=Acudir.Clients.Dev
    ports:
      - "5001:5001"